server:
  port: 8080

spring:
  application:
    name: config-admin

logging:
  level:
    com.search: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
